// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopProject.Services;

#nullable disable

namespace PetShopProject.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20221113161211_Zoo")]
    partial class Zoo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetShopProject.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Descripition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 5,
                            CategoryId = 1,
                            Descripition = "Python is a genus of constricting snakes in the Pythonidae family native to the tropics and subtropics of the Eastern Hemisphere. The name Python was proposed by François Marie Daudin in 1803 for non-venomous flecked snakes. Currently, 10 python species are recognized as valid taxa.",
                            Name = "Python",
                            PictureName = "https://images.foxtv.com/static.fox10phoenix.com/www.fox10phoenix.com/content/uploads/2021/07/764/432/MyLove-the-snake-crop-3-Courtesy-of-Jay-Brewer.jpg?ve=1&tl=1"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 12,
                            CategoryId = 2,
                            Descripition = "Monitor lizards are lizards in the genus Varanus, the only extant genus in the family Varanidae. They are native to Africa, Asia, and Oceania, and one species is also found in the Americas as an invasive species. About 80 species are recognized.\r\n\r\nMonitor lizards have long necks, powerful tails and claws, and well-developed limbs. The adult length of extant species ranges from 20 cm (7.9 in) in some species, to over 3 m (10 ft) in the case of the Komodo dragon, though the extinct varanid known as megalania (Varanus priscus) may have been capable of reaching lengths more than 7 m (23 ft). Most monitor species are terrestrial, but arboreal and semiaquatic monitors are also known. While most monitor lizards are carnivorous, eating eggs, smaller reptiles, fish, birds, insects, and small mammals, some also eat fruit and vegetation, depending on where they live.",
                            Name = "Monitor Lizard",
                            PictureName = "https://a-z-animals.com/media/2018/09/Monitor-lizard-header.jpg"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 2,
                            CategoryId = 3,
                            Descripition = "The sugar glider (Petaurus breviceps) is a small, omnivorous, arboreal, and nocturnal gliding possum belonging to the marsupial infraclass. The common name refers to its predilection for sugary foods such as sap and nectar and its ability to glide through the air, much like a flying squirrel. They have very similar habits and appearance to the flying squirrel, despite not being closely related",
                            Name = "sugar glider",
                            PictureName = "https://www.wilderness.org.au/images/uploads/2ACH01R-1-Alamy-sugar-glider-CROP.jpg"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 90,
                            CategoryId = 4,
                            Descripition = "The gray whale (Eschrichtius robustus), also known as the grey whale, gray back whale, Pacific gray whale, Korean gray whale, or California gray whale, is a baleen whale that migrates between feeding and breeding grounds yearly. It reaches a length of 14.9 meters (49 ft), a weight of up to 41 tonnes (90,000 lb) and lives between 55 and 70 years, although one female was estimated to be 75–80 years of age. The common name of the whale comes from the gray patches and white mottling on its dark skin. Gray whales were once called devil fish because of their fighting behavior when hunted. The gray whale is the sole living species in the genus Eschrichtius.",
                            Name = "grey whale",
                            PictureName = "i dont know"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 20,
                            CategoryId = 1,
                            Descripition = "The okapi (/oʊˈkɑːpiː/; Okapia johnstoni), also known as the forest giraffe, Congolese giraffe, or zebra giraffe, is an artiodactyl mammal that is endemic to the northeast Democratic Republic of the Congo in central Africa. It is the only species in the genus Okapia. Although the okapi has striped markings reminiscent of zebras, it is most closely related to the giraffe. The okapi and the giraffe are the only living members of the family Giraffidae.\r\n\r\nThe okapi stands about 1.5 m (4 ft 11 in) tall at the shoulder and has a typical body length around 2.5 m (8 ft 2 in). Its weight ranges from 200 to 350 kg (440 to 770 lb). It has a long neck, and large, flexible ears. Its coat is a chocolate to reddish brown, much in contrast with the white horizontal stripes and rings on the legs, and white ankles. Male okapis have short, distinct horn-like protuberances on their heads called ossicones, less than 15 cm (5.9 in) in length. Females possess hair whorls, and ossicones are absent.",
                            Name = "Okapi",
                            PictureName = "i dont know"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 42,
                            CategoryId = 4,
                            Descripition = "The goblin shark (Mitsukurina owstoni) is a rare species of deep-sea shark. Sometimes called a \"living fossil\", it is the only extant representative of the family Mitsukurinidae, a lineage some 125 million years old. This pink-skinned animal has a distinctive profile with an elongated, flat snout, and highly protrusible jaws containing prominent nail-like teeth. It is usually between 3 and 4 m (10 and 13 ft) long when mature, though it can grow considerably larger such as one captured in 2000 that is thought to have measured 6 m (20 ft). Goblin sharks are benthopelagic creatures that inhabit upper continental slopes, submarine canyons, and seamounts throughout the world at depths greater than 100 m (330 ft), with adults found deeper than juveniles. Some researchers believe that these sharks could also dive to depths of up to 1,300 m (4,270 ft), for short periods of time.",
                            Name = "Goblin Shark",
                            PictureName = "i dont know"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = 42,
                            CategoryId = 2,
                            Descripition = "The goblin shark (Mitsukurina owstoni) is a rare species of deep-sea shark. Sometimes called a \"living fossil\", it is the only extant representative of the family Mitsukurinidae, a lineage some 125 million years old. This pink-skinned animal has a distinctive profile with an elongated, flat snout, and highly protrusible jaws containing prominent nail-like teeth. It is usually between 3 and 4 m (10 and 13 ft) long when mature, though it can grow considerably larger such as one captured in 2000 that is thought to have measured 6 m (20 ft). Goblin sharks are benthopelagic creatures that inhabit upper continental slopes, submarine canyons, and seamounts throughout the world at depths greater than 100 m (330 ft), with adults found deeper than juveniles. Some researchers believe that these sharks could also dive to depths of up to 1,300 m (4,270 ft), for short periods of time.",
                            Name = "pacu fish",
                            PictureName = "i dont know"
                        });
                });

            modelBuilder.Entity("PetShopProject.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "mamals"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "reptiles"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "avian"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "fish"
                        });
                });

            modelBuilder.Entity("PetShopProject.Models.Comments", b =>
                {
                    b.Property<int>("CommentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentsId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Descripition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CommentsId");

                    b.HasIndex("AnimalId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentsId = 1,
                            AnimalId = 1,
                            Descripition = "very scry animal"
                        },
                        new
                        {
                            CommentsId = 2,
                            AnimalId = 2,
                            Descripition = "poisaning animal"
                        },
                        new
                        {
                            CommentsId = 3,
                            AnimalId = 3,
                            Descripition = "cute animal"
                        },
                        new
                        {
                            CommentsId = 4,
                            AnimalId = 4,
                            Descripition = "huge animal"
                        },
                        new
                        {
                            CommentsId = 5,
                            AnimalId = 5,
                            Descripition = "cool animal"
                        },
                        new
                        {
                            CommentsId = 6,
                            AnimalId = 6,
                            Descripition = "scary animal"
                        },
                        new
                        {
                            CommentsId = 7,
                            AnimalId = 7,
                            Descripition = "dangerous animal"
                        });
                });

            modelBuilder.Entity("PetShopProject.Models.Animal", b =>
                {
                    b.HasOne("PetShopProject.Models.Category", "Category")
                        .WithMany("Animals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PetShopProject.Models.Comments", b =>
                {
                    b.HasOne("PetShopProject.Models.Animal", "Animal")
                        .WithMany("Comments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PetShopProject.Models.Animal", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("PetShopProject.Models.Category", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
